const teamInfo = {
    "2676a": {"team_abbreviation": "AUA", "initial_ranking": 200}, //Austin Anarchy (A)
    "2685a": {"team_abbreviation": "CWB", "initial_ranking": 425}, //Carolina Wreckingballs (A)
    "2686a": {"team_abbreviation": "CBRD", "initial_ranking": 300}, //Casco Bay Roller Derby (A)
    "2686b": {"team_abbreviation": "CBRD(B)", "initial_ranking": 40}, //Casco Bay Roller Derby (B)
    "2687a": {"team_abbreviation": "CBB", "initial_ranking": 400}, //Chicago Bruise Brothers (A)
    "2687b": {"team_abbreviation": "CBB(B)", "initial_ranking": 40}, //Chicago Bruise Brothers (B)
    "2689a": {"team_abbreviation": "CGRD", "initial_ranking": 50}, //Cleveland Guardians Roller Derby (A)
    "2692a": {"team_abbreviation": "CTB", "initial_ranking": 250}, //Crash Test Brummies (A)
    "2693a": {"team_abbreviation": "DGC", "initial_ranking": 1000}, //Denver Ground Control (A)
    "2694a": {"team_abbreviation": "DMRD", "initial_ranking": 80}, //Detroit Mens Roller Derby (A)
    "2696a": {"team_abbreviation": "ChCRD", "initial_ranking": 250}, //Chinook City Roller Derby (A)
    "2699a": {"team_abbreviation": "CRD", "initial_ranking": 450, "distance_clause_applies": true}, //Concussion Roller Derby (A)
    "2699b": {"team_abbreviation": "CRD(B)", "initial_ranking": 100, "distance_clause_applies": true}, //Concussion Roller Derby (B)
    "2701a": {"team_abbreviation": "MCM", "initial_ranking": 900}, //Magic City Misfits (A)
    "2702a": {"team_abbreviation": "MRD", "initial_ranking": 600}, //Manchester Roller Derby (A)
    "2702b": {"team_abbreviation": "MRD(B)", "initial_ranking": 100}, //Manchester Roller Derby (B)
    "2714a": {"team_abbreviation": "PAN", "initial_ranking": 250}, //Panam Squad (A)
    "2715a": {"team_abbreviation": "PHH", "initial_ranking": 250}, //Philadelphia Hooligans (A)
    "2715b": {"team_abbreviation": "PHH(B)", "initial_ranking": 150}, //Philadelphia Hooligans (B)
    "2717a": {"team_abbreviation": "PSOD", "initial_ranking": 350, "distance_clause_applies": true}, //Puget Sound Outcast Derby (A)
    "2719a": {"team_abbreviation": "RCR", "initial_ranking": 425}, //Race City Rebels (A)
    "2723a": {"team_abbreviation": "SDA", "initial_ranking": 650, "distance_clause_applies": true}, //San Diego Aftershocks (A)
    "2723b": {"team_abbreviation": "SDA(B)", "initial_ranking": 120, "distance_clause_applies": true}, //San Diego Aftershocks (B)
    "2725a": {"team_abbreviation": "SWS", "initial_ranking": 250}, //South Wales Silures (A)
    "2727a": {"team_abbreviation": "SLGK", "initial_ranking": 1200}, //Saint Louis Gatekeepers (A)
    "2727b": {"team_abbreviation": "SLGK(B)", "initial_ranking": 180}, //Saint Louis Gatekeepers (B)
    "2733a": {"team_abbreviation": "TIL", "initial_ranking": 500}, //The Inhuman League (A)
    "2735a": {"team_abbreviation": "TMRD", "initial_ranking": 300}, //Toronto Mens Roller Derby (A)
    "2737a": {"team_abbreviation": "TNF", "initial_ranking": 600}, //Tyne and Fear Roller Derby (A)
    "2737b": {"team_abbreviation": "TNF(B)", "initial_ranking": 100}, //Tyne and Fear Roller Derby (B)
    "3013a": {"team_abbreviation": "TRD", "initial_ranking": 50}, //Terminus Roller Derby (A)
    "13122a": {"team_abbreviation": "KMRD", "initial_ranking": 450}, //Kent Mens Roller Derby (A)
    "17403a": {"team_abbreviation": "PIT", "initial_ranking": 300}, //Pittsburgh Roller Derby (A)
    "17403b": {"team_abbreviation": "PIT(B)", "initial_ranking": 40}, //Pittsburgh Roller Derby (B)
    "17404a": {"team_abbreviation": "DHR", "initial_ranking": 200}, //D.H.R. Men's Roller Derby (A)
    "17405a": {"team_abbreviation": "FCF", "initial_ranking": 100}, //Flour City Roller Derby (A)
    "17908a": {"team_abbreviation": "DIS", "initial_ranking": 450, "distance_clause_applies": true}, //Disorder (A)
    "17909a": {"team_abbreviation": "BBRD", "initial_ranking": 600}, //Borderland Bandits Roller Derby (A)
    "17910a": {"team_abbreviation": "NDT", "initial_ranking": 600}, //Nordicks de Touraine (A)
    "17911a": {"team_abbreviation": "RDT", "initial_ranking": 800}, //Roller Derby Toulouse (A)
    "17912a": {"team_abbreviation": "TMP", "initial_ranking": 140}, //Tampa Roller Derby (A)
    "17913a": {"team_abbreviation": "SDRD", "initial_ranking": 500}, //Southern Discomfort Roller Derby (A)
    "17914a": {"team_abbreviation": "DDD", "initial_ranking": 250}, //Dallas Derby Devils (A)
    "17915a": {"team_abbreviation": "RDNA", "initial_ranking": 500}, //Roller Derby Nantes Atlantique (A)
    "17916a": {"team_abbreviation": "ORD", "initial_ranking": 300}, //Orcet Roller Derby (A)
    "17917a": {"team_abbreviation": "WRD", "initial_ranking": 264}, //Wirral Roller Derby (A)
}